# Generated by Django 2.2.8 on 2020-02-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200228_0621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryFactsModel',
        ),
    ]
